### ISSUE TITLE
API change

### ISSUE THREAD

**Issue by ekkithump** [MasterSoft24/Grive2#7]
Google have changed the API, so grive is broken. Does grive2 still use the same code as grive ? It looks like it does.

**Comment by MasterSoft24** [comment]
Yes. It's true. Maybe later I'll deal with it

**Comment by pageauc** [comment]
libgrive/test/data/entry.xml as well as others code have the old api entry points.  The revised api url access points are per link below.  There are also changed api endpoint interface naming changes needed to communicate with the new api.  See google migration reference here https://developers.google.com/drive/web/migration.  

google also states in the migration reference
"The Drive API v2 is built on Google's new JSON-based API infrastructure, which is not backward compatible with the XML-based Documents List API v3."
So not sure if this will be an issue as well.

I am willing to help with this project since I would like to see it running on Raspberry Pi again.  Currently trying GDriveFS written in python.  This works OK but does not seem to run headless as far as my testing so far.  Hopefully the API and resource changes can be resolved so grive will work again.
Thanks for your Support
Claude ...
